#!/usr/bin/python

import sys
import os

if len(sys.argv) == 3:
    os.system('rsync --info=progress2 ' + sys.argv[1] + ' ' + sys.argv[2])
elif len(sys.argv) == 4:
    os.system('rsync --info=progress2 ' + sys.argv[1] + ' ' + sys.argv[2] + ' ' + sys.argv[3])
else:
    print 'Invalid arguments.'
    print 'Usage: ' + os.path.basename(sys.argv[0]) + ' <flags> <source> <destination>'
